laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('cars','CarController');

laravel/app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Brand extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $fillable = ['name'];

    public function cars()
    {
        return $this->hasMany('App\Car');
    }
}

laravel/app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Car extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $fillable = ['model','quantity','price','brand_id'];

    public function brand()
    {
        return $this->belongsTo('App\Brand');
    }
}

laravel/app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Role extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    protected $fillable = ['description'];

    public function users()
    {
        return $this->hasMany('App\User');
    }

}

laravel/app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use SoftDeletes;
    use Notifiable;
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role()
    {
        return $this->belongsTo('App\Role');
    }

    public function isAdmin()
    {
        if ($this->role->id === 1) {
            return true;
        }
        return false;
    }

}

laravel/app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Brand;

use App\Http\Requests\StoreCar;
use App\Http\Requests\UpdateCar;


use App\Repositories\CarRepository as ICrud;

class CarController extends Controller
{
    protected $carRepository;

    public function __construct(ICrud $_carRepository)
    {
        $this->carRepository = $_carRepository;
        $this->middleware('auth');
        $this->middleware('admin')->except('index');
    }


    public function index()
    {
        try {

            $cars = $this->carRepository->all();
            return view('car.index', compact('cars', $cars));
        } catch (\Exception $ex) {
            $msg = __('exceptionMsg');
            return view('car.index')->with('msg', $msg);
        }

    }


    public function create()
    {
        try {
            $brands = $this->carRepository->getBrands();
            if (!count($brands) > 0) {
                $msg = __('noBrandsFound');
                return redirect()->action('HomeController@index')->with('msg', $msg);
            }
            return view('car.create', compact('brands', $brands));
        } catch (\Exception $ex) {
            $msg = __('exceptionMsg');
            return redirect()->action('CarController@index')->with('msg', $msg);
        }
    }


    public function store(StoreCar $request)
    {
        try {

            $this->carRepository->store($request);
            return redirect()->action('CarController@index');
        } catch (\Exception $ex) {
            $msg = __('exceptionMsg');
            return redirect()->action('CarController@index')->with('msg', $msg);
        }

    }

    public function edit($id)
    {
        try {
            $car = $this->carRepository->find($id);
            $brands = $this->carRepository->getBrands();
            if (!count($brands) > 0) {
                $msg = __('noBrandsFound');
                return redirect()->action('HomeController@index')->with('msg', $msg);
            }
            return view('car.edit')->with('car', $car)->with('brands', $brands);
        } catch (\Exception $ex) {
            $msg = __('exceptionMsg');
            return redirect()->action('CarController@index')->with('msg', $msg);
        }
    }


    public function update(UpdateCar $request, $id)
    {
        try {

            $this->carRepository->update($request, $id);
            return redirect()->action('CarController@index');
        } catch (\Exception $ex) {
            $msg = __('exceptionMsg');
            return redirect()->action('CarController@index')->with('msg', $msg);
        }

    }

    public function destroy($id)
    {
        try {

            $this->carRepository->destroy($id);
            return redirect()->action('CarController@index');

        } catch (\Exception $ex) {
            $msg = __('exceptionMsg');
            return redirect()->action('CarController@index')->with('msg', $msg);
        }
    }
}

laravel/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

laravel/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

laravel/resources/views/car/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-header">{{ __('labels.New') }}</div>

        <div class="card-body">
            @include('partials.car._createForm')
        </div>
    </div>
@endsection

laravel/resources/views/car/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-header">{{ __('Editar') }}</div>

        <div class="card-body">
            @include('partials.car._editForm')
        </div>
    </div>
@endsection

laravel/resources/views/car/index.blade.php
@extends('layouts.app')
@section('content')
    @if(session('msg'))
        <div class="alert alert-danger">
            <p>{{session('msg')}}</p>
        </div>
    @elseif(count($cars)>0)

        @include('partials.car._indexTable')
        @include('partials.car._indexTableFilterScript')

    @else
        <div class="text-center">
            <p>{{__('noRecordsFound')}}</p>
        </div>
    @endif
@endsection

laravel/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    @if(session('msg'))
        <div class="col-md-8 offset-2">
            <div class="alert alert-danger">
                <p>{{session('msg')}}</p>
            </div>
        </div>
    @endif

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    {{__('youAreLoggedIn',['Name'=>Auth::user()->name])}}
                </div>
            </div>
        </div>
    </div>

@endsection

laravel/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                @auth
                    @if(Auth::user()->isAdmin())
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                                   aria-expanded="false">
                                    <i title="car" class="fas fa-car fa-sm"></i>
                                    {{__('labels.Cars')}} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li><a class="dropdown-item" href="{{ route('cars.index') }}"><i
                                                class="fas fa-list fa-sm"></i>{{__('labels.List')}}</a>
                                    </li>
                                    <li><a class="dropdown-item" href="{{ route('cars.create') }}"><i
                                                class="fas fa-plus fa-sm"></i> {{__('labels.New')}}</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    @else
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item dropdown">
                                <a href="{{ route('cars.index') }}" class="nav-link" role="button"
                                   aria-expanded="false">
                                    {{__('labels.Cars')}}
                                </a>
                            </li>
                        </ul>
                @endif
            @endauth
            <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('labels.Login') }}</a>
                        </li>
                        <li class="nav-item">
                            @if (Route::has('register'))
                                <a class="nav-link" href="{{ route('register') }}">{{ __('labels.Register') }}</a>
                            @endif
                        </li>
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('labels.Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>
    <main class="py-4">
        <div class="container-fluid">
            <div class="col-md-8 offset-md-2">
                @yield('content')
            </div>
        </div>

    </main>
</div>
</body>
</html>

laravel/resources/views/partials/car/_createForm.blade.php
<form method="POST" action="{{ route('cars.store') }}">
    @csrf
    <div class="form-group row">
        <label for="model" class="col-md-4 col-form-label text-md-right">{{ __('labels.Model') }}</label>

        <div class="col-md-6">
            <input id="model" type="text"
                   class="form-control{{ $errors->has('model') ? ' is-invalid' : '' }}"
                   name="model" value="{{ old('model') }}" required autofocus>

            @if ($errors->has('model'))
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('model') }}</strong>
                                    </span>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="quantity"
               class="col-md-4 col-form-label text-md-right">{{ __('labels.Quantity') }}</label>

        <div class="col-md-6">
            <input id="quantity" type="number" step="0"
                   class="form-control{{ $errors->has('quantity') ? ' is-invalid' : '' }}" name="quantity"
                   value="{{ old('quantity') }}" required>

            @if ($errors->has('quantity'))
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('quantity') }}</strong>
                                    </span>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('labels.Price') }}</label>

        <div class="col-md-6">
            <input id="price" type="number" step="0.01"
                   class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}" name="price"
                   value="{{ old('price') }}" required>

            @if ($errors->has('price'))
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
            @endif
        </div>
    </div>
    @if(isset($brands))
        <div class="form-group row">
            <label for="role" class="col-md-4 col-form-label text-md-right">{{ __('labels.Brand') }}</label>
            <div class="col-md-6">
                <select value="{{ old('brand_id') }}" required name="brand_id" type="number" id="brand_id"
                        class="form-control{{ $errors->has('brand_id') ? ' is-invalid' : '' }}">
                    @foreach($brands as $brand)
                        <option value="{{$brand->id}}">{{$brand->name}}</option>
                    @endforeach
                </select>

                @if ($errors->has('brand_id'))
                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('brand_id') }}</strong>
                                    </span>
                @endif
            </div>
        </div>
    @endif
    <div class="form-group row mb-0">
        <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
                {{ __('labels.Save') }}
            </button>
        </div>
    </div>
</form>

laravel/resources/views/partials/car/_editForm.blade.php
<form method="POST" action="{{ route('cars.update',$car->id) }}">
    @method('PUT')
    @csrf

    <div class="form-group row">
        <label for="model" class="col-md-4 col-form-label text-md-right">{{ __('Modelo') }}</label>

        <div class="col-md-6">
            <input id="model" type="text"
                   class="form-control{{ $errors->has('model') ? ' is-invalid' : '' }}"
                   name="model" value="{{$car->model }}" required autofocus>

            @if ($errors->has('model'))
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('model') }}</strong>
                                    </span>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="quantity" class="col-md-4 col-form-label text-md-right">{{ __('Quantidade') }}</label>

        <div class="col-md-6">
            <input id="quantity" type="number" step="0"
                   class="form-control{{ $errors->has('quantity') ? ' is-invalid' : '' }}" name="quantity"
                   value="{{$car->quantity }}" required>

            @if ($errors->has('quantity'))
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('quantity') }}</strong>
                                    </span>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Preço') }}</label>

        <div class="col-md-6">
            <input id="price" type="number" step="0.01"
                   class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}" name="price"
                   value="{{$car->price }}" required>

            @if ($errors->has('price'))
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
            @endif
        </div>
    </div>
    @if(isset($brands))
        <div class="form-group row">
            <label for="role" class="col-md-4 col-form-label text-md-right">{{ __('Role') }}</label>

            <div class="col-md-6">
                <select required name="brand_id" type="number" id="brand_id"
                        class="form-control{{ $errors->has('brand_id') ? ' is-invalid' : '' }}">
                    @foreach($brands as $brand)
                        @if($brand->id==$car->brand_id)
                            <option selected value="{{$brand->id}}">{{$brand->name}}</option>
                        @else
                            <option value="{{$brand->id}}">{{$brand->name}}</option>
                        @endif
                    @endforeach
                </select>

                @if ($errors->has('brand_id'))
                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('brand_id') }}</strong>
                                    </span>
                @endif
            </div>
        </div>
    @endif
    <div class="form-group row mb-0">
        <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
                {{ __('Atualizar') }}
            </button>
        </div>
    </div>
</form>

laravel/resources/views/partials/car/_indexTable.blade.php
<div class="row">
    <input id="term" onkeyup="filterTable()" name="term" autofocus placeholder="{{__('labels.Filter')}}..."
           type="text"
           class="form-control">
</div>
<br>
<div class="row">
    <table id="table" class="table table-sm  table-condensed table-hover">
        <caption>{{__('labels.ListOfCars')}}</caption>
        <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>{{__('labels.Model')}}</th>
            <th>{{__('labels.Quantity')}}</th>
            <th>{{__('labels.Brand')}}</th>
            <th>{{__('labels.Price')}}</th>
            @if(Auth::user()->isAdmin())
                <th>{{__('labels.Actions')}}</th>
            @endif
        </tr>
        </thead>
        <tbody>
        @foreach($cars as $car)
            <tr>
                <td>{{$car->id}}</td>
                <td>{{ $car->model }}</td>
                <td>{{ $car->quantity }}</td>
                <td>{{ $car->brand->name }}</td>
                <td>R$ {{ $car->price }}</td>
                @if(Auth::user()->isAdmin())
                    <td>
                        <a href="{{route('cars.edit',$car->id)}}">
                            <button class="btn btn-sm btn-primary" type="button">{{__('labels.Edit')}}</button>
                        </a>
                        <form method="POST" action="{{route('cars.destroy',$car->id)}}">
                            @method('DELETE')
                            @csrf
                            <button class="btn btn-sm btn-danger" type="submit">{{__('labels.Delete')}}</button>
                        </form>
                    </td>
                @endif
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

laravel/resources/views/partials/car/_indexTableFilterScript.blade.php
<script>
    function filterTable() {
        var input = document.getElementById("term");
        var filter = input.value.toUpperCase();
        var rows = document.querySelector("#table tbody").rows;
        for (var i = 0; i < rows.length; i++) {
            var firstCol = rows[i].cells[0].textContent.toUpperCase();
            var secondCol = rows[i].cells[1].textContent.toUpperCase();
            var thirdCol = rows[i].cells[4].textContent.toUpperCase();
            if (firstCol.indexOf(filter) > -1 || secondCol.indexOf(filter) > -1 || thirdCol.indexOf(filter) > -1) {
                rows[i].style.display = "";
            } else {
                rows[i].style.display = "none";
            }
        }
    }
</script>